name: Django                                  # workflow name

on:
  push:
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
      - run: |
           echo "This is an integration step"
           echo "$GITHUB_RUN_ID"
      - run: exit 1
        continue-on-error: true
